name: envx
description: Compile-time environment configuration resolver for Dart and Flutter.
version: 1.0.0
repository: https://github.com/arlamend7/dart_envx
homepage: https://github.com/arlamend7/dart_envx
issue_tracker: https://github.com/arlamend7/dart_envx/issues
documentation: https://arlamend7.github.io/dart_envx/docs
license: MIT
example: example/envx_example.dart
topics:
  - environment
  - configuration

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
