name: envx
description: Compile-time environment configuration resolver for Dart and Flutter.
version: 1.0.1
repository: https://github.com/example/envx
homepage: https://github.com/example/envx
issue_tracker: https://github.com/example/envx/issues
documentation: https://example.com/envx/docs
topics:
  - environment
  - configuration

environment:
  sdk: ^3.8.1

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
